export const HttpStatusCodes = {
  OK: 200 /** Request succeeded */,
  CREATED: 201 /** Resource created */,
  NO_CONTENT: 204 /** Request succeeded but no content */,
  NOT_ACCEPTABLE: 406 /** Content not acceptable */,
  PRECONDITION_FAILED: 412 /** Precondition failed */,
  UNPROCESSABLE_ENTITY: 422 /** Unprocessable entity */,
  BAD_REQUEST: 400 /** Invalid request */,
  UNAUTHORIZED: 401 /** Authentication required or failed */,
  FORBIDDEN: 403 /** Access denied */,
  NOT_FOUND: 404 /** Resource not found */,
  METHOD_NOT_ALLOWED: 405 /** HTTP method not supported */,
  REQUEST_TIMEOUT: 408 /** Request timed out */,
  CONFLICT: 409 /** Conflict, e.g., duplicate data */,
  UNSUPPORTED_MEDIA_TYPE: 415 /** Unsupported content type */,
  TOO_MANY_REQUESTS: 429 /** Rate limit exceeded */,
  INTERNAL_SERVER_ERROR: 500 /** Server error */,
  BAD_GATEWAY: 502 /** Invalid response from upstream */,
  SERVICE_UNAVAILABLE: 503 /** Server unavailable */,
  GATEWAY_TIMEOUT: 504 /** Upstream server timed out */,
} as const
